Additionally pull up the following revision for ticket #192, to fix the build:
	src/sys/kern/kern_time.c	1.199

mark a variable __diagused to fix this problem affecting many builds:

kern/kern_time.c:1413:6: error: variable 'error' set but not used
[-Werror=unused-but-set-variable]